<a href="https://colab.research.google.com/github/vaishnavanil541-cmd/data-science-L1/blob/main/Anil_Ai(14).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 50 Pandas Operations Questions — Google Colab Assignment

## A. Loading and Exploring the Dataset

### Q2. Display the first 5 rows of the dataset.

In [ ]:
csv_files = ["students.csv"]
e = 0
df = pd.read_csv(csv_files[e])

In [ ]:
df.head(5)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8 48.2,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5 78.7 48.4,NaN,54.0,6.76,...,3.6,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes
2,DS003,Aditya Gupta,Female,20.0,7,75.3,1.1 96.8 73.8,NaN,60.1,5.08,...,1.8,101,3,Beginner,Medium,35.7,69.1,C,Low,Video Tutorials and Quizzes
3,DS004,Aditya Kumar,Male,21.0,4,84.8,2.6 73.6 72.8,NaN,47.0,9.65,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6 66.4 56.3,NaN,88.9,6.71,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes

### Q3. Display the last 10 rows of the dataset.

In [ ]:
df.tail(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.4,...,7.5,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,2.2,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q4. Find the number of rows and columns in the DataFrame.

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 200
Columns: 21

### Q5. Display all column names.

In [ ]:
print(df.columns.tolist())

['student_id', 'student_name', 'gender', 'age', 'semester', 'attendance_percent', 'study_hours_per_day', 'assignment_average', 'quiz_average', 'mid_sem_score', 'previous_cgpa', 'lab_hours_per_week', 'online_activity_count', 'projects_completed', 'python_skill_level', 'mathematics_skill', 'engagement_score', 'predicted_score', 'grade', 'risk_level', 'learning_recommendation']

### Q6. Display the data type of every column.

In [ ]:
print(df.dtypes)

student_id                  object
student_name                object
gender                      object
age                        float64
semester                     int64
attendance_percent         float64
study_hours_per_day         object
assignment_average         float64
quiz_average               float64
mid_sem_score              float64
previous_cgpa              float64
lab_hours_per_week         float64
online_activity_count        int64
projects_completed           int64
python_skill_level          object
mathematics_skill           object
engagement_score           float64
predicted_score            float64
grade                       object
risk_level                  object
learning_recommendation     object
dtype: object

### Q7. Use df.info() to display a concise summary of the dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               200 non-null    object
 1   student_name             200 non-null    object
 2   gender                   200 non-null    object
 3   age                      198 non-null    float64
 4   semester                 200 non-null    int64
 5   attendance_percent       200 non-null    float64
 6   study_hours_per_day      200 non-null    object
 7   assignment_average       159 non-null    float64
 8   quiz_average             200 non-null    float64
 9   mid_sem_score            199 non-null    float64
 10  previous_cgpa            156 non-null    float64
 11  lab_hours_per_week       199 non-null    float64
 12  online_activity_count    200 non-null    int64
 13  projects_completed       200 non-null    int64
 14  python_skill_level       200 non-null    object
 15  mathematics_skill        191 non-null    object
 16  engagement_score         200 non-null    float64
 17  predicted_score          200 non-null    float64
 18  grade                    200 non-null    object
 19  risk_level               200 non-null    object
 20  learning_recommendation  200 non-null    object
dtypes: float64(9), int64(3), object(9)
memory usage: 32.9+ KB

### Q8. Generate descriptive statistics for all numerical columns.

In [ ]:
df.describe()

,age,semester,attendance_percent,assignment_average,quiz_average,mid_sem_score,previous_cgpa,lab_hours_per_week,online_activity_count,projects_completed,engagement_score,predicted_score
count,198.000000,200.000000,200.000000,159.000000,200.000000,199.000000,156.000000,199.000000,200.000000,200.000000,200.000000,200.000000
mean,20.590909,5.580000,77.457500,73.310692,69.270000,52.769146,7.369615,3.973367,108.105000,2.330000,55.441500,77.891000
std,1.744991,1.657509,12.294528,16.657015,18.017789,29.266812,1.427444,2.184413,54.821446,1.656751,12.934494,7.911789
min,18.000000,3.000000,55.000000,45.000000,35.700000,5.080000,5.040000,0.000000,10.000000,0.000000,26.700000,60.000000
25%,19.000000,4.000000,67.150000,59.250000,53.800000,37.150000,6.135000,2.200000,58.000000,1.000000,46.350000,71.675000
50%,21.000000,6.000000,77.950000,74.200000,69.850000,56.200000,7.460000,3.800000,110.000000,2.000000,54.900000,78.150000
75%,22.000000,7.000000,88.500000,89.400000,84.125000,76.000000,8.655000,5.700000,156.000000,4.000000,66.425000,83.825000
max,23.000000,8.000000,99.800000,99.800000,99.900000,98.000000,9.790000,8.000000,200.000000,5.000000,83.800000,96.300000

### Q9. Check whether the dataset contains any missing values.

In [ ]:
print(df.isnull().sum())
print("\nAny missing values:", df.isnull().values.any())

student_id                  0
student_name                0
gender                      0
age                         2
semester                    0
attendance_percent          0
study_hours_per_day         0
assignment_average         41
quiz_average                0
mid_sem_score               1
previous_cgpa              44
lab_hours_per_week          1
online_activity_count       0
projects_completed          0
python_skill_level          0
mathematics_skill           9
engagement_score            0
predicted_score             0
grade                       0
risk_level                  0
learning_recommendation     0
dtype: int64

Any missing values: True

### Q10. Find the number of unique values in each column.

In [ ]:
print(df.nunique())

student_id                 200
student_name               123
gender                       2
age                          6
semester                     6
attendance_percent         166
study_hours_per_day         94
assignment_average         137
quiz_average               176
mid_sem_score              177
previous_cgpa              137
lab_hours_per_week          75
online_activity_count      130
projects_completed           6
python_skill_level           3
mathematics_skill            3
engagement_score           170
predicted_score            146
grade                        4
risk_level                   3
learning_recommendation      4
dtype: int64

## B. Selecting and Accessing Data

### Q11. Select and display only the student_name, gender, and semester columns.

In [ ]:
df[["student_name", "gender", "semester"]]

      student_name  gender  semester
0     Nisha Pandey    Male         7
1    Aarav Chauhan  Female         7
2     Aditya Gupta  Female         7
3     Aditya Kumar    Male         4
4      Neha Pandey  Female         6
..             ...     ...       ...
195    Aarav Verma  Female         6
196  Arjun Chauhan    Male         3
197     Neha Kumar  Female         4
198    Priya Gupta    Male         7
199   Vivaan Singh    Male         7

[200 rows x 3 columns]

### Q12. Display all students who are in Semester 3.

In [ ]:
df[df["semester"] == 3]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3 60.4,93.0,83.6,9.57,...,2.6,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects
18,DS019,Aarav Sharma,Female,NaN,3,72.8,5.2 96.2 44.2,NaN,48.6,8.22,...,2.9,136,2,Beginner,Medium,70.7,80.9,B,Medium,Practice Exercises
31,DS032,Ananya Singh,Male,21.0,3,89.3,4.1 50.6,45.0,80.6,5.35,...,6.6,131,1,Beginner,Low,65.6,70.0,C,Low,Video Tutorials and Quizzes
38,DS039,Riya Kumar,Female,19.0,3,73.7,2.4 91.9,NaN,87.8,9.80,...,8.0,190,4,Intermediate,High,52.8,84.7,B,Medium,Practice Exercises
39,DS040,Riya Gupta,Male,23.0,3,60.8,5.8 78.3 53.7,NaN,78.7,7.97,...,NaN,81,1,Intermediate,Medium,68.1,84.2,B,High,Practice Exercises
44,DS045,Rahul Kumar,Male,22.0,3,71.0,5.5 52.1 59.8,NaN,55.9,5.44,...,3.8,65,5,Beginner,Medium,67.0,70.0,C,Medium,Video Tutorials and Quizzes
60,DS061,Kunal Chauhan,Male,21.0,3,55.2,2.7,66.9,72.2,94.80,...,2.8,171,2,Intermediate,Medium,49.1,75.6,B,High,Practice Exercises
64,DS065,Simran Mishra,Male,22.0,3,79.8,2.3,NaN,70.3,73.70,...,4.6,60,0,Intermediate,Medium,43.1,71.6,C,Low,Video Tutorials and Quizzes
77,DS078,Riya Gupta,Male,21.0,3,81.1,2.4,66.9,45.5,56.90,...,5.9,186,2,Intermediate,Medium,54.4,68.9,C,Low,Video Tutorials and Quizzes
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.10,...,1.1,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice
95,DS096,Saurabh Mishra,Female,21.0,3,97.8,1.6,94.3,75.7,75.10,...,2.4,17,1,Intermediate,High,38.6,83.9,B,Low,Practice Exercises
101,DS102,Aditya Gupta,Female,22.0,3,89.8,1.7,98.3,67.2,50.30,...,1.4,102,1,Intermediate,Low,44.2,70.7,C,Low,Video Tutorials and Quizzes
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.80,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
115,DS116,Vivaan Kumar,Female,22.0,3,63.0,2.6,57.7,52.4,76.50,...,5.1,194,5,Beginner,Medium,52.1,66.6,C,High,Video Tutorials and Quizzes
117,DS118,Arjun Sharma,Male,18.0,3,65.2,2.8,48.8,71.1,39.40,...,1.9,158,5,Intermediate,Medium,51.3,69.6,C,Medium,Video Tutorials and Quizzes
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.60,...,1.4,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects
138,DS139,Saurabh Singh,Female,20.0,3,80.0,4.7,78.9,51.3,58.10,...,4.4,95,1,Intermediate,Low,65.2,81.9,B,Low,Practice Exercises
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.80,...,7.5,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.50,...,7.4,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice
149,DS150,Saurabh Sinha,Male,23.0,3,78.6,1.6,92.3,83.4,39.40,...,4.3,107,0,Intermediate,Low,41.0,77.1,B,Low,Practice Exercises
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.50,...,7.2,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.50,...,4.4,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.20,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.50,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.10,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects

### Q13. Display all female students.

In [ ]:
df[df["gender"].str.lower() == "female"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5 78.7 48.4,NaN,54.0,6.76,...,3.6,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes
2,DS003,Aditya Gupta,Female,20.0,7,75.3,1.1 96.8 73.8,NaN,60.1,5.08,...,1.8,101,3,Beginner,Medium,35.7,69.1,C,Low,Video Tutorials and Quizzes
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6 66.4 56.3,NaN,88.9,6.71,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes
6,DS007,Aarav Mishra,Female,23.0,7,87.8,4.2 93.8 68.3,NaN,42.8,8.42,...,6.1,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises
7,DS008,Sneha Sharma,Female,18.0,6,80.3,4.5 52.7 76.3,NaN,70.1,5.97,...,7.5,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.30,...,4.7,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.50,...,5.0,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.90,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes

### Q14. Find students whose previous_cgpa is greater than 8.0.

In [ ]:
df[df["previous_cgpa"] > 8.0]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
50,DS051,Vivaan Pandey,Female,19.0,5,92.7,2.0,98.2,82.7,48.0,...,4.2,10,1,Intermediate,Low,40.0,83.0,B,Low,Practice Exercises
52,DS053,Ananya Pandey,Male,23.0,5,70.7,5.6,90.7,97.9,43.1,...,7.5,85,2,Beginner,Medium,69.3,90.2,A,Medium,Advanced Projects
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
56,DS057,Rohan Chauhan,Female,18.0,8,92.0,1.6,91.6,47.6,60.8,...,1.2,56,3,Intermediate,Medium,40.3,77.4,B,Low,Practice Exercises
58,DS059,Simran Sinha,Female,18.0,6,81.7,1.5,95.5,87.4,36.5,...,6.2,40,1,Beginner,Low,35.6,77.3,B,Low,Practice Exercises
59,DS060,Aryan Sinha,Female,23.0,5,75.3,1.6,99.2,90.3,43.1,...,7.0,64,2,Intermediate,Medium,36.7,82.6,B,Low,Practice Exercises
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.3,...,3.4,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
78,DS079,Arjun Singh,Female,23.0,7,56.9,1.1,99.3,65.7,60.0,...,1.7,46,4,Beginner,Medium,26.7,74.2,C,High,Video Tutorials and Quizzes
79,DS080,Kavya Pandey,Male,20.0,8,82.6,1.8,NaN,53.9,96.3,...,4.9,119,1,Beginner,NaN,44.6,83.7,B,Low,Practice Exercises
86,DS087,Rahul Sharma,Female,23.0,4,74.5,5.2,66.6,50.8,84.0,...,1.4,77,2,Beginner,High,66.4,84.9,B,Medium,Practice Exercises
87,DS088,Saurabh Yadav,Male,18.0,8,82.9,1.2,92.9,98.4,98.0,...,1.0,134,3,Beginner,Low,41.0,90.6,A,Low,Advanced Projects
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.6,...,4.2,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
93,DS094,Ananya Sinha,Female,18.0,6,90.1,1.2,71.4,46.3,50.7,...,1.1,89,5,Intermediate,Medium,39.2,72.7,C,Low,Video Tutorials and Quizzes
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
102,DS103,Nisha Pandey,Male,20.0,6,86.8,1.8,54.2,42.2,82.9,...,3.8,129,3,Intermediate,High,46.4,71.7,C,Low,Video Tutorials and Quizzes
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
110,DS111,Priya Gupta,Female,19.0,7,66.1,3.4,66.7,73.0,83.5,...,4.2,30,2,Beginner,Medium,46.1,81.9,B,Medium,Practice Exercises
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
113,DS114,Nisha Verma,Female,23.0,8,79.8,1.2,79.8,97.1,74.1,...,7.1,146,1,Beginner,Medium,41.2,84.1,B,Low,Practice Exercises
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.6,...,6.1,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects
117,DS118,Arjun Sharma,Male,18.0,3,65.2,2.8,48.8,71.1,39.4,...,1.9,158,5,Intermediate,Medium,51.3,69.6,C,Medium,Video Tutorials and Quizzes
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.7,...,1.9,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects
120,DS121,Priya Kumar,Female,18.0,8,78.4,4.1,49.9,85.3,43.3,...,6.3,151,3,Intermediate,Medium,64.5,78.8,B,Low,Practice Exercises
121,DS122,Kunal Gupta,Female,19.0,5,65.8,3.5,90.4,56.8,96.3,...,1.3,159,2,Intermediate,Medium,57.2,87.9,A,Medium,Advanced Projects
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.4,...,2.4,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects
125,DS126,Ananya Singh,Female,21.0,5,72.4,3.8,55.5,52.7,66.5,...,5.0,92,0,Beginner,Low,55.9,75.5,B,Medium,Practice Exercises
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.8,...,1.9,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises
138,DS139,Saurabh Singh,Female,20.0,3,80.0,4.7,78.9,51.3,58.1,...,4.4,95,1,Intermediate,Low,65.2,81.9,B,Low,Practice Exercises
139,DS140,Kavya Sinha,Male,19.0,7,71.6,2.6,53.2,58.3,92.0,...,2.9,134,3,Intermediate,High,49.4,80.5,B,Medium,Practice Exercises
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.8,...,7.5,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises
144,DS145,Sneha Sharma,Male,22.0,5,66.7,3.1,93.0,90.5,47.1,...,3.7,14,3,Beginner,Low,42.6,83.6,B,Medium,Practice Exercises
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.1,...,7.7,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises
149,DS150,Saurabh Sinha,Male,23.0,3,78.6,1.6,92.3,83.4,39.4,...,4.3,107,0,Intermediate,Low,41.0,77.1,B,Low,Practice Exercises
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.1,...,7.0,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects
153,DS154,Saurabh Pandey,Female,21.0,6,89.1,2.4,62.2,78.6,47.7,...,4.2,69,3,Intermediate,NaN,47.0,78.4,B,Low,Practice Exercises
154,DS155,Aditya Sharma,Female,20.0,4,62.6,3.5,77.9,42.0,58.6,...,6.6,110,3,Intermediate,High,52.5,73.8,C,High,Video Tutorials and Quizzes
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.5,...,7.2,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.7,...,6.7,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.3,...,5.4,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises
169,DS170,Sneha Kumar,Male,21.0,5,73.5,5.5,84.3,76.5,55.1,...,7.6,17,0,Intermediate,Low,63.7,88.7,A,Medium,Advanced Projects
171,DS172,Kunal Mishra,Male,19.0,7,85.5,2.8,77.7,40.6,76.3,...,4.9,37,2,Intermediate,Low,46.7,80.3,B,Low,Practice Exercises
176,DS177,Kavya Yadav,Female,20.0,5,62.2,1.1,86.6,67.5,53.8,...,0.9,179,3,Intermediate,High,38.7,74.7,C,High,Video Tutorials and Quizzes
178,DS179,Isha Sharma,Male,19.0,4,66.7,2.0,48.2,60.5,52.6,...,4.5,138,3,Intermediate,High,43.7,70.2,C,Medium,Video Tutorials and Quizzes
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
186,DS187,Aryan Sharma,Male,23.0,6,81.0,4.5,45.3,46.1,91.5,...,0.9,171,1,Beginner,NaN,69.9,79.1,B,Low,Practice Exercises
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.5,...,4.4,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,2.2,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q15. Display students whose attendance_percent is below 75%.

In [ ]:
df[df["attendance_percent"] < 75]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,1.8 48.2,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,2.5 78.7 48.4,NaN,54.0,6.76,...,3.6,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes
4,DS005,Neha Pandey,Female,23.0,6,57.0,2.6 66.4 56.3,NaN,88.9,6.71,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes
5,DS006,Aman Sinha,Male,18.0,6,68.2,1.1 55.9 82.7,NaN,86.4,7.91,...,7.4,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes
10,DS011,Nisha Mishra,Female,19.0,5,68.5,2.4 47 76.6,NaN,67.7,5.25,...,2.2,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,DS183,Isha Gupta,Male,23.0,5,73.3,5.1,87.0,74.4,97.10,...,0.9,125,4,Intermediate,High,69.1,87.2,A,Medium,Advanced Projects
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.50,...,5.0,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.10,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises

### Q16. Find students who study more than 4 hours per day.

In [ ]:
df["study_hours_per_day"] = pd.to_numeric(df["study_hours_per_day"], errors="coerce")
df[df["study_hours_per_day"] > 4]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
47,DS048,Priya Sinha,Female,18.0,7,81.7,4.4,88.4,69.9,40.6,...,4.7,17,0,Intermediate,Medium,57.0,80.0,B,Low,Practice Exercises
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
52,DS053,Ananya Pandey,Male,23.0,5,70.7,5.6,90.7,97.9,43.1,...,7.5,85,2,Beginner,Medium,69.3,90.2,A,Medium,Advanced Projects
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.3,...,2.5,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects
61,DS062,Isha Yadav,Female,18.0,6,73.9,5.6,64.9,74.8,76.1,...,5.3,90,3,Intermediate,Medium,70.5,78.4,B,Medium,Practice Exercises
65,DS066,Kavya Pandey,Male,23.0,5,98.3,5.7,52.8,64.4,56.1,...,5.1,170,4,Beginner,Low,83.8,75.2,B,Low,Practice Exercises
67,DS068,Priya Pandey,Female,18.0,4,80.5,5.9,70.9,50.9,66.5,...,5.9,34,0,Beginner,High,70.0,81.6,B,Low,Practice Exercises
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.5,...,2.8,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
80,DS081,Riya Chauhan,Male,20.0,8,91.0,4.1,56.9,71.1,73.8,...,2.1,172,1,Intermediate,High,69.3,80.8,B,Low,Practice Exercises
83,DS084,Riya Singh,Male,22.0,8,81.7,5.1,64.1,80.7,71.8,...,7.0,156,3,Advanced,High,73.7,81.6,B,Low,Practice Exercises
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.5,...,7.0,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises
86,DS087,Rahul Sharma,Female,23.0,4,74.5,5.2,66.6,50.8,84.0,...,1.4,77,2,Beginner,High,66.4,84.9,B,Medium,Practice Exercises
89,DS090,Kavya Verma,Male,23.0,5,67.3,5.8,53.3,65.9,96.3,...,5.1,15,2,Beginner,NaN,64.4,83.3,B,Medium,Practice Exercises
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
97,DS098,Isha Mishra,Female,23.0,6,88.5,5.4,68.9,42.6,45.5,...,5.2,46,0,Intermediate,Low,69.0,69.2,C,Low,Video Tutorials and Quizzes
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
99,DS100,Vivaan Verma,Female,19.0,4,90.7,4.3,99.6,57.0,58.3,...,3.7,30,0,Beginner,Medium,59.5,81.8,B,Low,Practice Exercises
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.6,...,3.9,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.8,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
116,DS117,Simran Sharma,Male,19.0,8,75.1,4.6,45.9,60.5,88.2,...,2.7,41,4,Beginner,Low,58.9,79.7,B,Low,Practice Exercises
118,DS119,Aditya Yadav,Female,23.0,4,99.7,4.3,75.7,83.8,65.2,...,4.5,45,4,Beginner,Medium,62.9,80.6,B,Low,Practice Exercises
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.7,...,1.9,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects
120,DS121,Priya Kumar,Female,18.0,8,78.4,4.1,49.9,85.3,43.3,...,6.3,151,3,Intermediate,Medium,64.5,78.8,B,Low,Practice Exercises
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.9,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
128,DS129,Rohan Kumar,Male,22.0,7,92.5,4.1,55.9,43.9,37.8,...,2.1,148,4,Advanced,Low,67.8,67.3,C,Low,Video Tutorials and Quizzes
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
130,DS131,Aarav Chauhan,Female,19.0,4,66.4,4.9,90.4,69.7,60.1,...,1.8,154,3,Intermediate,High,68.1,82.0,B,Medium,Practice Exercises
131,DS132,Priya Kumar,Male,22.0,7,56.7,4.7,81.2,88.1,41.8,...,4.1,67,5,Advanced,High,57.1,73.0,C,High,Video Tutorials and Quizzes
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.6,...,1.4,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.0,...,2.0,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes
138,DS139,Saurabh Singh,Female,20.0,3,80.0,4.7,78.9,51.3,58.1,...,4.4,95,1,Intermediate,Low,65.2,81.9,B,Low,Practice Exercises
147,DS148,Arjun Singh,Male,18.0,5,70.6,5.5,46.2,79.8,97.6,...,7.5,179,1,Intermediate,Medium,76.0,86.3,A,Medium,Advanced Projects
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.1,...,7.7,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.1,...,7.0,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects
155,DS156,Kunal Mishra,Male,18.0,7,99.3,4.3,79.9,50.0,92.3,...,1.3,36,4,Intermediate,Medium,62.1,84.9,B,Low,Practice Exercises
156,DS157,Nisha Singh,Male,19.0,8,72.1,5.9,63.5,57.8,94.7,...,6.1,130,2,Advanced,Medium,75.6,80.3,B,Medium,Practice Exercises
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.1,...,2.5,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises
164,DS165,Rohan Verma,Female,22.0,5,77.0,4.7,73.9,42.0,91.5,...,7.6,17,4,Intermediate,Low,58.2,75.5,B,Low,Practice Exercises
169,DS170,Sneha Kumar,Male,21.0,5,73.5,5.5,84.3,76.5,55.1,...,7.6,17,0,Intermediate,Low,63.7,88.7,A,Medium,Advanced Projects
175,DS176,Riya Kumar,Male,23.0,7,78.9,5.2,76.9,73.6,41.8,...,7.8,167,2,Intermediate,Low,74.7,75.7,B,Low,Practice Exercises
177,DS178,Simran Sinha,Female,18.0,7,68.0,5.8,66.4,63.1,57.1,...,1.2,58,4,Intermediate,High,68.0,79.7,B,Medium,Practice Exercises
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.0,...,1.6,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects
182,DS183,Isha Gupta,Male,23.0,5,73.3,5.1,87.0,74.4,97.1,...,0.9,125,4,Intermediate,High,69.1,87.2,A,Medium,Advanced Projects
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
185,DS186,Neha Gupta,Male,22.0,7,92.0,5.0,93.6,82.0,41.8,...,5.8,137,3,Intermediate,Low,74.0,84.6,B,Low,Practice Exercises
186,DS187,Aryan Sharma,Male,23.0,6,81.0,4.5,45.3,46.1,91.5,...,0.9,171,1,Beginner,NaN,69.9,79.1,B,Low,Practice Exercises
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.5,...,5.0,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.1,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects

### Q17. Display students with python_skill_level equal to 'Advanced'.

In [ ]:
df[df["python_skill_level"].str.lower() == "advanced"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,NaN,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
3,DS004,Aditya Kumar,Male,21.0,4,84.8,NaN,NaN,47.0,9.65,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
5,DS006,Aman Sinha,Male,18.0,6,68.2,NaN,NaN,86.4,7.91,...,7.4,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes
12,DS013,Aditya Verma,Female,21.0,5,64.9,NaN,NaN,41.3,9.51,...,3.2,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises
13,DS014,Simran Mishra,Male,23.0,4,66.6,NaN,NaN,69.4,6.16,...,0.7,149,4,Advanced,Medium,63.0,79.9,B,Medium,Practice Exercises
14,DS015,Kunal Sharma,Male,20.0,5,93.5,NaN,NaN,95.8,8.77,...,5.4,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,NaN,NaN,39.6,8.08,...,0.2,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,NaN,NaN,37.1,6.34,...,3.3,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,NaN,NaN,70.6,7.16,...,7.3,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises
46,DS047,Aditya Mishra,Male,23.0,5,78.9,1.5,69.6,72.0,50.80,...,3.0,48,0,Advanced,Low,35.6,67.0,C,Low,Video Tutorials and Quizzes
48,DS049,Rahul Verma,Male,19.0,4,66.0,3.5,63.2,96.0,35.50,...,2.9,121,3,Advanced,Low,54.2,70.5,C,Medium,Video Tutorials and Quizzes
63,DS064,Simran Singh,Male,23.0,6,76.6,3.5,87.1,46.2,56.70,...,6.0,19,1,Advanced,Medium,48.7,69.2,C,Low,Video Tutorials and Quizzes
66,DS067,Simran Singh,Female,18.0,7,70.4,2.3,65.9,75.4,52.40,...,3.3,146,1,Advanced,Medium,47.7,72.9,C,Medium,Video Tutorials and Quizzes
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.30,...,3.4,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects
81,DS082,Aditya Yadav,Male,22.0,7,79.2,4.0,76.9,45.5,92.00,...,1.0,146,2,Advanced,High,63.5,77.8,B,Low,Practice Exercises
83,DS084,Riya Singh,Male,22.0,8,81.7,5.1,64.1,80.7,71.80,...,7.0,156,3,Advanced,High,73.7,81.6,B,Low,Practice Exercises
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.50,...,7.0,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.90,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.80,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.80,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
111,DS112,Neha Sinha,Female,21.0,5,72.1,2.0,71.4,51.7,45.80,...,4.2,36,4,Advanced,Medium,36.9,67.7,C,Medium,Video Tutorials and Quizzes
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
128,DS129,Rohan Kumar,Male,22.0,7,92.5,4.1,55.9,43.9,37.80,...,2.1,148,4,Advanced,Low,67.8,67.3,C,Low,Video Tutorials and Quizzes
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.50,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
131,DS132,Priya Kumar,Male,22.0,7,56.7,4.7,81.2,88.1,41.80,...,4.1,67,5,Advanced,High,57.1,73.0,C,High,Video Tutorials and Quizzes
132,DS133,Aman Sharma,Male,21.0,5,62.8,1.5,81.3,85.9,52.20,...,0.7,90,0,Advanced,Medium,34.9,66.5,C,High,Video Tutorials and Quizzes
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.80,...,1.9,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.60,...,1.4,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.00,...,2.0,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.40,...,5.6,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes
143,DS144,Neha Yadav,Female,23.0,6,72.3,3.9,77.3,51.1,58.50,...,0.2,122,5,Advanced,Medium,59.0,72.5,C,Medium,Video Tutorials and Quizzes
156,DS157,Nisha Singh,Male,19.0,8,72.1,5.9,63.5,57.8,94.70,...,6.1,130,2,Advanced,Medium,75.6,80.3,B,Medium,Practice Exercises
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.10,...,2.5,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.70,...,1.0,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.00,...,1.6,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects
181,DS182,Isha Chauhan,Male,21.0,6,89.0,3.5,61.6,69.5,69.00,...,3.5,164,2,Advanced,Medium,63.4,79.1,B,Low,Practice Exercises
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.40,...,7.5,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.20,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.90,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.30,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q18. Display all students who obtained grade 'A'.

In [ ]:
df[df["grade"].str.upper() == "A"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
14,DS015,Kunal Sharma,Male,20.0,5,93.5,NaN,NaN,95.8,8.77,...,5.4,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects
16,DS017,Isha Yadav,Female,23.0,8,81.5,NaN,NaN,63.2,6.68,...,5.2,120,0,Beginner,Medium,77.2,87.1,A,Low,Advanced Projects
17,DS018,Arjun Sharma,Male,18.0,3,99.8,NaN,93.0,83.6,9.57,...,2.6,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects
19,DS020,Aarav Sinha,Female,20.0,8,71.2,NaN,NaN,91.4,9.38,...,4.1,66,3,Intermediate,Medium,43.1,91.1,A,Medium,Advanced Projects
28,DS029,Saurabh Gupta,Female,18.0,5,99.6,NaN,NaN,57.2,9.47,...,6.9,122,4,Intermediate,Medium,59.5,85.9,A,Low,Advanced Projects
35,DS036,Neha Kumar,Female,22.0,8,81.3,NaN,NaN,96.8,9.27,...,3.6,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.40,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
52,DS053,Ananya Pandey,Male,23.0,5,70.7,5.6,90.7,97.9,43.10,...,7.5,85,2,Beginner,Medium,69.3,90.2,A,Medium,Advanced Projects
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.20,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.30,...,2.5,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.30,...,3.4,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.50,...,2.8,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.70,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
87,DS088,Saurabh Yadav,Male,18.0,8,82.9,1.2,92.9,98.4,98.00,...,1.0,134,3,Beginner,Low,41.0,90.6,A,Low,Advanced Projects
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.80,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.90,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.60,...,3.9,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.80,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.80,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.00,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.60,...,6.1,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.70,...,1.9,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects
121,DS122,Kunal Gupta,Female,19.0,5,65.8,3.5,90.4,56.8,96.30,...,1.3,159,2,Intermediate,Medium,57.2,87.9,A,Medium,Advanced Projects
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.40,...,2.4,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.70,...,6.1,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.50,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.00,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.60,...,1.4,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects
147,DS148,Arjun Singh,Male,18.0,5,70.6,5.5,46.2,79.8,97.60,...,7.5,179,1,Intermediate,Medium,76.0,86.3,A,Medium,Advanced Projects
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.10,...,7.0,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.70,...,6.7,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects
169,DS170,Sneha Kumar,Male,21.0,5,73.5,5.5,84.3,76.5,55.10,...,7.6,17,0,Intermediate,Low,63.7,88.7,A,Medium,Advanced Projects
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.00,...,1.6,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects
182,DS183,Isha Gupta,Male,23.0,5,73.3,5.1,87.0,74.4,97.10,...,0.9,125,4,Intermediate,High,69.1,87.2,A,Medium,Advanced Projects
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.50,...,4.4,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.10,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.10,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.90,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.30,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q19. Find students whose risk_level is 'High'.

In [ ]:
df[df["risk_level"].str.lower() == "high"]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,NaN,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
4,DS005,Neha Pandey,Female,23.0,6,57.0,NaN,NaN,88.9,6.71,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes
12,DS013,Aditya Verma,Female,21.0,5,64.9,NaN,NaN,41.3,9.51,...,3.2,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises
20,DS021,Kavya Sharma,Female,21.0,4,59.2,NaN,NaN,70.3,6.38,...,4.7,95,0,Beginner,High,53.6,69.8,C,High,Video Tutorials and Quizzes
33,DS034,Aditya Singh,Female,21.0,8,57.5,NaN,79.0,83.5,7.80,...,7.7,200,3,Beginner,High,43.2,72.4,C,High,Video Tutorials and Quizzes
37,DS038,Isha Gupta,Female,18.0,4,58.7,NaN,NaN,61.7,8.73,...,3.8,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises
39,DS040,Riya Gupta,Male,23.0,3,60.8,NaN,NaN,78.7,7.97,...,NaN,81,1,Intermediate,Medium,68.1,84.2,B,High,Practice Exercises
45,DS046,Arjun Kumar,Male,18.0,5,63.3,2.0,65.4,69.1,75.20,...,3.7,118,1,Beginner,Medium,41.3,70.7,C,High,Video Tutorials and Quizzes
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.40,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
60,DS061,Kunal Chauhan,Male,21.0,3,55.2,2.7,66.9,72.2,94.80,...,2.8,171,2,Intermediate,Medium,49.1,75.6,B,High,Practice Exercises
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.70,...,6.5,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice
78,DS079,Arjun Singh,Female,23.0,7,56.9,1.1,99.3,65.7,60.00,...,1.7,46,4,Beginner,Medium,26.7,74.2,C,High,Video Tutorials and Quizzes
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.50,...,7.0,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.60,...,4.2,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.80,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
91,DS092,Simran Verma,Female,20.0,7,60.9,1.2,95.6,77.0,86.80,...,0.9,26,5,Intermediate,Medium,26.9,78.7,B,High,Practice Exercises
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.90,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
100,DS101,Saurabh Singh,Female,22.0,7,58.1,3.2,50.4,64.3,73.50,...,5.3,79,0,Intermediate,NaN,46.4,72.1,C,High,Video Tutorials and Quizzes
103,DS104,Priya Verma,Female,19.0,8,57.6,3.7,96.5,42.4,42.90,...,7.5,78,0,Intermediate,Low,50.2,70.6,C,High,Video Tutorials and Quizzes
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.60,...,3.9,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects
109,DS110,Riya Sharma,Male,21.0,8,58.3,4.0,81.8,77.2,65.10,...,6.9,57,1,Intermediate,Low,51.1,78.2,B,High,Practice Exercises
115,DS116,Vivaan Kumar,Female,22.0,3,63.0,2.6,57.7,52.4,76.50,...,5.1,194,5,Beginner,Medium,52.1,66.6,C,High,Video Tutorials and Quizzes
124,DS125,Sneha Gupta,Male,19.0,7,56.2,1.7,98.0,73.0,97.80,...,2.5,87,3,Intermediate,Low,34.6,80.5,B,High,Practice Exercises
131,DS132,Priya Kumar,Male,22.0,7,56.7,4.7,81.2,88.1,41.80,...,4.1,67,5,Advanced,High,57.1,73.0,C,High,Video Tutorials and Quizzes
132,DS133,Aman Sharma,Male,21.0,5,62.8,1.5,81.3,85.9,52.20,...,0.7,90,0,Advanced,Medium,34.9,66.5,C,High,Video Tutorials and Quizzes
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.10,...,7.7,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises
154,DS155,Aditya Sharma,Female,20.0,4,62.6,3.5,77.9,42.0,58.60,...,6.6,110,3,Intermediate,High,52.5,73.8,C,High,Video Tutorials and Quizzes
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.50,...,7.2,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.70,...,1.0,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.90,...,6.6,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.30,...,5.4,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises
172,DS173,Rahul Sharma,Female,23.0,4,55.5,3.1,61.2,69.2,72.50,...,1.0,58,0,Intermediate,Medium,43.3,67.1,C,High,Video Tutorials and Quizzes
173,DS174,Ananya Singh,Female,21.0,5,58.5,3.7,92.4,75.4,49.70,...,3.6,181,0,Intermediate,Medium,58.7,76.3,B,High,Practice Exercises
176,DS177,Kavya Yadav,Female,20.0,5,62.2,1.1,86.6,67.5,53.80,...,0.9,179,3,Intermediate,High,38.7,74.7,C,High,Video Tutorials and Quizzes
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.50,...,5.0,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises

### Q20. Display the student_name and predicted_score for students with predicted_score greater than 80.

In [ ]:
df.loc[df["predicted_score"] > 80, ["student_name", "predicted_score"]]

      student_name  predicted_score
3     Aditya Kumar             80.1
6     Aarav Mishra             83.6
11    Rahul Mishra             81.2
12    Aditya Verma             82.2
14    Kunal Sharma             95.9
..             ...              ...
190   Riya Chauhan             83.6
191     Isha Sinha             87.6
196  Arjun Chauhan             86.8
198    Priya Gupta             92.6
199   Vivaan Singh             89.3

[81 rows x 2 columns]

## C. Filtering with Multiple Conditions

### Q21. Find students in Semester 4 with attendance_percent greater than 80%.

In [ ]:
df[(df["semester"] == 4) & (df["attendance_percent"] > 80)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
3,DS004,Aditya Kumar,Male,21.0,4,84.8,NaN,NaN,47.0,9.65,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
27,DS028,Riya Chauhan,Male,22.0,4,85.7,NaN,NaN,80.0,6.67,...,7.5,129,3,Intermediate,High,53.3,75.3,B,Low,Practice Exercises
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,NaN,NaN,70.6,7.16,...,7.3,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises
42,DS043,Saurabh Pandey,Female,18.0,4,89.6,NaN,NaN,57.6,NaN,...,4.6,124,0,Intermediate,Medium,42.7,65.3,C,Low,Video Tutorials and Quizzes
67,DS068,Priya Pandey,Female,18.0,4,80.5,5.9,70.9,50.9,66.50,...,5.9,34,0,Beginner,High,70.0,81.6,B,Low,Practice Exercises
76,DS077,Simran Kumar,Male,22.0,4,94.4,3.1,70.4,99.4,35.00,...,3.1,105,2,Beginner,Low,56.8,74.6,C,Low,Video Tutorials and Quizzes
99,DS100,Vivaan Verma,Female,19.0,4,90.7,4.3,99.6,57.0,58.30,...,3.7,30,0,Beginner,Medium,59.5,81.8,B,Low,Practice Exercises
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.80,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
118,DS119,Aditya Yadav,Female,23.0,4,99.7,4.3,75.7,83.8,65.20,...,4.5,45,4,Beginner,Medium,62.9,80.6,B,Low,Practice Exercises
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.70,...,6.1,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.40,...,5.6,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.70,...,6.7,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects
163,DS164,Arjun Verma,Male,21.0,4,85.1,4.0,94.1,51.1,40.10,...,6.4,167,3,Intermediate,High,66.6,73.0,C,Low,Video Tutorials and Quizzes
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.40,...,7.5,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.90,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes

### Q22. Find students whose previous_cgpa is greater than 8.0 and predicted_score is greater than 75.

In [ ]:
df[(df["previous_cgpa"] > 8.0) & (df["predicted_score"] > 75)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
50,DS051,Vivaan Pandey,Female,19.0,5,92.7,2.0,98.2,82.7,48.0,...,4.2,10,1,Intermediate,Low,40.0,83.0,B,Low,Practice Exercises
52,DS053,Ananya Pandey,Male,23.0,5,70.7,5.6,90.7,97.9,43.1,...,7.5,85,2,Beginner,Medium,69.3,90.2,A,Medium,Advanced Projects
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
56,DS057,Rohan Chauhan,Female,18.0,8,92.0,1.6,91.6,47.6,60.8,...,1.2,56,3,Intermediate,Medium,40.3,77.4,B,Low,Practice Exercises
58,DS059,Simran Sinha,Female,18.0,6,81.7,1.5,95.5,87.4,36.5,...,6.2,40,1,Beginner,Low,35.6,77.3,B,Low,Practice Exercises
59,DS060,Aryan Sinha,Female,23.0,5,75.3,1.6,99.2,90.3,43.1,...,7.0,64,2,Intermediate,Medium,36.7,82.6,B,Low,Practice Exercises
69,DS070,Rahul Pandey,Male,19.0,6,83.5,3.5,76.5,90.3,61.3,...,3.4,139,3,Advanced,Low,60.0,86.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
79,DS080,Kavya Pandey,Male,20.0,8,82.6,1.8,NaN,53.9,96.3,...,4.9,119,1,Beginner,NaN,44.6,83.7,B,Low,Practice Exercises
86,DS087,Rahul Sharma,Female,23.0,4,74.5,5.2,66.6,50.8,84.0,...,1.4,77,2,Beginner,High,66.4,84.9,B,Medium,Practice Exercises
87,DS088,Saurabh Yadav,Male,18.0,8,82.9,1.2,92.9,98.4,98.0,...,1.0,134,3,Beginner,Low,41.0,90.6,A,Low,Advanced Projects
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.6,...,4.2,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.8,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.9,...,6.1,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
110,DS111,Priya Gupta,Female,19.0,7,66.1,3.4,66.7,73.0,83.5,...,4.2,30,2,Beginner,Medium,46.1,81.9,B,Medium,Practice Exercises
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.0,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
113,DS114,Nisha Verma,Female,23.0,8,79.8,1.2,79.8,97.1,74.1,...,7.1,146,1,Beginner,Medium,41.2,84.1,B,Low,Practice Exercises
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.6,...,6.1,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.7,...,1.9,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects
120,DS121,Priya Kumar,Female,18.0,8,78.4,4.1,49.9,85.3,43.3,...,6.3,151,3,Intermediate,Medium,64.5,78.8,B,Low,Practice Exercises
121,DS122,Kunal Gupta,Female,19.0,5,65.8,3.5,90.4,56.8,96.3,...,1.3,159,2,Intermediate,Medium,57.2,87.9,A,Medium,Advanced Projects
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.4,...,2.4,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects
125,DS126,Ananya Singh,Female,21.0,5,72.4,3.8,55.5,52.7,66.5,...,5.0,92,0,Beginner,Low,55.9,75.5,B,Medium,Practice Exercises
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.5,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.8,...,1.9,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises
138,DS139,Saurabh Singh,Female,20.0,3,80.0,4.7,78.9,51.3,58.1,...,4.4,95,1,Intermediate,Low,65.2,81.9,B,Low,Practice Exercises
139,DS140,Kavya Sinha,Male,19.0,7,71.6,2.6,53.2,58.3,92.0,...,2.9,134,3,Intermediate,High,49.4,80.5,B,Medium,Practice Exercises
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.8,...,7.5,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises
144,DS145,Sneha Sharma,Male,22.0,5,66.7,3.1,93.0,90.5,47.1,...,3.7,14,3,Beginner,Low,42.6,83.6,B,Medium,Practice Exercises
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.1,...,7.7,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises
149,DS150,Saurabh Sinha,Male,23.0,3,78.6,1.6,92.3,83.4,39.4,...,4.3,107,0,Intermediate,Low,41.0,77.1,B,Low,Practice Exercises
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.1,...,7.0,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects
153,DS154,Saurabh Pandey,Female,21.0,6,89.1,2.4,62.2,78.6,47.7,...,4.2,69,3,Intermediate,NaN,47.0,78.4,B,Low,Practice Exercises
159,DS160,Aditya Verma,Female,19.0,3,64.7,2.8,48.8,85.8,61.5,...,7.2,154,0,Intermediate,Medium,50.9,75.7,B,High,Practice Exercises
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.7,...,6.7,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.3,...,5.4,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises
169,DS170,Sneha Kumar,Male,21.0,5,73.5,5.5,84.3,76.5,55.1,...,7.6,17,0,Intermediate,Low,63.7,88.7,A,Medium,Advanced Projects
171,DS172,Kunal Mishra,Male,19.0,7,85.5,2.8,77.7,40.6,76.3,...,4.9,37,2,Intermediate,Low,46.7,80.3,B,Low,Practice Exercises
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.0,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
186,DS187,Aryan Sharma,Male,23.0,6,81.0,4.5,45.3,46.1,91.5,...,0.9,171,1,Beginner,NaN,69.9,79.1,B,Low,Practice Exercises
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.5,...,4.4,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects
192,DS193,Saurabh Mishra,Male,22.0,7,94.4,1.9,60.3,47.8,78.9,...,2.2,93,2,Intermediate,High,46.2,78.0,B,Low,Practice Exercises
193,DS194,Rohan Yadav,Male,21.0,3,76.4,1.6,79.9,86.2,35.2,...,1.5,150,3,Advanced,Medium,43.9,76.3,B,Low,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q23. Find students who are either in Semester 2 or Semester 4.

In [ ]:
df[df["semester"].isin([2, 4])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
3,DS004,Aditya Kumar,Male,21.0,4,84.8,NaN,NaN,47.0,9.65,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
13,DS014,Simran Mishra,Male,23.0,4,66.6,NaN,NaN,69.4,6.16,...,0.7,149,4,Advanced,Medium,63.0,79.9,B,Medium,Practice Exercises
20,DS021,Kavya Sharma,Female,21.0,4,59.2,NaN,NaN,70.3,6.38,...,4.7,95,0,Beginner,High,53.6,69.8,C,High,Video Tutorials and Quizzes
27,DS028,Riya Chauhan,Male,22.0,4,85.7,NaN,NaN,80.0,6.67,...,7.5,129,3,Intermediate,High,53.3,75.3,B,Low,Practice Exercises
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,NaN,NaN,37.1,6.34,...,3.3,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice
37,DS038,Isha Gupta,Female,18.0,4,58.7,NaN,NaN,61.7,8.73,...,3.8,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,NaN,NaN,70.6,7.16,...,7.3,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises
42,DS043,Saurabh Pandey,Female,18.0,4,89.6,NaN,NaN,57.6,NaN,...,4.6,124,0,Intermediate,Medium,42.7,65.3,C,Low,Video Tutorials and Quizzes
48,DS049,Rahul Verma,Male,19.0,4,66.0,3.5,63.2,96.0,35.50,...,2.9,121,3,Advanced,Low,54.2,70.5,C,Medium,Video Tutorials and Quizzes
67,DS068,Priya Pandey,Female,18.0,4,80.5,5.9,70.9,50.9,66.50,...,5.9,34,0,Beginner,High,70.0,81.6,B,Low,Practice Exercises
76,DS077,Simran Kumar,Male,22.0,4,94.4,3.1,70.4,99.4,35.00,...,3.1,105,2,Beginner,Low,56.8,74.6,C,Low,Video Tutorials and Quizzes
84,DS085,Sneha Sinha,Male,22.0,4,59.8,4.5,55.4,92.9,97.50,...,7.0,179,1,Advanced,Medium,65.3,84.8,B,High,Practice Exercises
86,DS087,Rahul Sharma,Female,23.0,4,74.5,5.2,66.6,50.8,84.00,...,1.4,77,2,Beginner,High,66.4,84.9,B,Medium,Practice Exercises
88,DS089,Neha Sharma,Female,20.0,4,55.0,1.8,70.8,96.7,41.60,...,4.2,38,4,Beginner,High,31.2,75.2,B,High,Practice Exercises
99,DS100,Vivaan Verma,Female,19.0,4,90.7,4.3,99.6,57.0,58.30,...,3.7,30,0,Beginner,Medium,59.5,81.8,B,Low,Practice Exercises
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.80,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.00,...,6.4,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects
114,DS115,Saurabh Pandey,Female,18.0,4,66.5,2.5,85.3,91.1,78.60,...,6.1,192,1,Beginner,Medium,52.0,86.5,A,Medium,Advanced Projects
118,DS119,Aditya Yadav,Female,23.0,4,99.7,4.3,75.7,83.8,65.20,...,4.5,45,4,Beginner,Medium,62.9,80.6,B,Low,Practice Exercises
123,DS124,Simran Verma,Male,19.0,4,92.0,1.7,92.4,95.4,66.70,...,6.1,134,3,Intermediate,Medium,47.3,85.0,A,Low,Advanced Projects
130,DS131,Aarav Chauhan,Female,19.0,4,66.4,4.9,90.4,69.7,60.10,...,1.8,154,3,Intermediate,High,68.1,82.0,B,Medium,Practice Exercises
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.80,...,1.9,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.40,...,5.6,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes
148,DS149,Rohan Chauhan,Male,22.0,4,61.5,4.6,55.5,60.3,55.10,...,7.7,198,0,Beginner,Medium,68.0,78.0,B,High,Practice Exercises
150,DS151,Pooja Sinha,Female,19.0,4,75.8,3.1,80.8,72.7,39.00,...,6.5,147,2,Beginner,High,55.5,74.1,C,Low,Video Tutorials and Quizzes
151,DS152,Aman Gupta,Female,21.0,4,69.9,4.8,73.6,52.3,92.10,...,7.0,164,4,Intermediate,High,69.0,87.4,A,Medium,Advanced Projects
154,DS155,Aditya Sharma,Female,20.0,4,62.6,3.5,77.9,42.0,58.60,...,6.6,110,3,Intermediate,High,52.5,73.8,C,High,Video Tutorials and Quizzes
161,DS162,Aryan Pandey,Male,23.0,4,98.5,1.6,83.9,98.4,88.70,...,6.7,182,5,Intermediate,Medium,52.0,89.9,A,Low,Advanced Projects
163,DS164,Arjun Verma,Male,21.0,4,85.1,4.0,94.1,51.1,40.10,...,6.4,167,3,Intermediate,High,66.6,73.0,C,Low,Video Tutorials and Quizzes
165,DS166,Priya Sinha,Female,20.0,4,62.4,1.9,97.1,66.7,86.30,...,5.4,101,3,Beginner,High,38.9,81.2,B,High,Practice Exercises
172,DS173,Rahul Sharma,Female,23.0,4,55.5,3.1,61.2,69.2,72.50,...,1.0,58,0,Intermediate,Medium,43.3,67.1,C,High,Video Tutorials and Quizzes
178,DS179,Isha Sharma,Male,19.0,4,66.7,2.0,48.2,60.5,52.60,...,4.5,138,3,Intermediate,High,43.7,70.2,C,Medium,Video Tutorials and Quizzes
190,DS191,Riya Chauhan,Male,22.0,4,87.2,4.0,94.3,75.0,65.40,...,7.5,73,4,Advanced,High,59.6,83.6,B,Low,Practice Exercises
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.10,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.90,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes

### Q24. Find students whose gender is Female and python_skill_level is Advanced.

In [ ]:
df[(df["gender"].str.lower() == "female") & (df["python_skill_level"].str.lower() == "advanced")]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
12,DS013,Aditya Verma,Female,21.0,5,64.9,NaN,NaN,41.3,9.51,...,3.2,48,1,Advanced,Medium,56.9,82.2,B,High,Practice Exercises
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,NaN,NaN,39.6,8.08,...,0.2,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,NaN,NaN,37.1,6.34,...,3.3,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,NaN,NaN,70.6,7.16,...,7.3,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises
66,DS067,Simran Singh,Female,18.0,7,70.4,2.3,65.9,75.4,52.40,...,3.3,146,1,Advanced,Medium,47.7,72.9,C,Medium,Video Tutorials and Quizzes
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.80,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
111,DS112,Neha Sinha,Female,21.0,5,72.1,2.0,71.4,51.7,45.80,...,4.2,36,4,Advanced,Medium,36.9,67.7,C,Medium,Video Tutorials and Quizzes
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.50,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
134,DS135,Vivaan Chauhan,Female,18.0,4,65.1,2.9,68.8,66.4,74.80,...,1.9,181,2,Advanced,Medium,54.0,81.0,B,Medium,Practice Exercises
137,DS138,Isha Mishra,Female,22.0,8,94.3,4.2,86.9,49.6,65.00,...,2.0,14,2,Advanced,Low,58.3,74.7,C,Low,Video Tutorials and Quizzes
141,DS142,Nisha Verma,Female,23.0,4,82.0,4.0,46.3,59.3,76.40,...,5.6,85,5,Advanced,Medium,59.3,70.8,C,Low,Video Tutorials and Quizzes
143,DS144,Neha Yadav,Female,23.0,6,72.3,3.9,77.3,51.1,58.50,...,0.2,122,5,Advanced,Medium,59.0,72.5,C,Medium,Video Tutorials and Quizzes
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.70,...,1.0,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises

### Q25. Find students whose study_hours_per_day is between 2 and 5 hours.

In [ ]:
df[df["study_hours_per_day"].between(2, 5)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
45,DS046,Arjun Kumar,Male,18.0,5,63.3,2.0,65.4,69.1,75.2,...,3.7,118,1,Beginner,Medium,41.3,70.7,C,High,Video Tutorials and Quizzes
47,DS048,Priya Sinha,Female,18.0,7,81.7,4.4,88.4,69.9,40.6,...,4.7,17,0,Intermediate,Medium,57.0,80.0,B,Low,Practice Exercises
48,DS049,Rahul Verma,Male,19.0,4,66.0,3.5,63.2,96.0,35.5,...,2.9,121,3,Advanced,Low,54.2,70.5,C,Medium,Video Tutorials and Quizzes
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.4,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
50,DS051,Vivaan Pandey,Female,19.0,5,92.7,2.0,98.2,82.7,48.0,...,4.2,10,1,Intermediate,Low,40.0,83.0,B,Low,Practice Exercises
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.5,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.3,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.1,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
197,DS198,Neha Kumar,Female,21.0,4,93.6,3.9,49.2,63.0,58.9,...,3.5,162,0,Intermediate,Medium,67.6,70.5,C,Low,Video Tutorials and Quizzes
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q26. Find students whose grade is either A or B.

In [ ]:
df[df["grade"].str.upper().isin(["A", "B"])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,NaN,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
3,DS004,Aditya Kumar,Male,21.0,4,84.8,NaN,NaN,47.0,9.65,...,6.2,171,1,Advanced,Medium,55.7,80.1,B,Low,Practice Exercises
6,DS007,Aarav Mishra,Female,23.0,7,87.8,NaN,NaN,42.8,8.42,...,6.1,151,2,Intermediate,Medium,67.6,83.6,B,Low,Practice Exercises
7,DS008,Sneha Sharma,Female,18.0,6,80.3,NaN,NaN,70.1,5.97,...,7.5,80,2,Intermediate,High,62.5,75.7,B,Low,Practice Exercises
11,DS012,Rahul Mishra,Female,21.0,5,71.6,NaN,NaN,98.9,6.91,...,6.5,153,0,Beginner,Medium,47.7,81.2,B,Medium,Practice Exercises
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,DS195,Rahul Yadav,Male,23.0,3,90.8,4.8,47.0,63.7,95.50,...,5.9,79,3,Beginner,Medium,67.4,78.2,B,Low,Practice Exercises
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.10,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.90,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.30,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

### Q27. Find students whose risk_level is either Medium or High.

In [ ]:
df[df["risk_level"].str.lower().isin(["medium", "high"])]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
0,DS001,Nisha Pandey,Male,22.0,7,62.0,NaN,92.0,74.1,8.40,...,0.2,11,3,Advanced,Low,30.8,75.2,B,High,Practice Exercises
1,DS002,Aarav Chauhan,Female,23.0,7,74.4,NaN,NaN,54.0,6.76,...,3.6,184,5,Beginner,Medium,53.3,68.3,C,Medium,Video Tutorials and Quizzes
4,DS005,Neha Pandey,Female,23.0,6,57.0,NaN,NaN,88.9,6.71,...,2.2,133,4,Beginner,High,45.7,71.6,C,High,Video Tutorials and Quizzes
5,DS006,Aman Sinha,Male,18.0,6,68.2,NaN,NaN,86.4,7.91,...,7.4,50,3,Advanced,Medium,29.9,74.8,C,Medium,Video Tutorials and Quizzes
10,DS011,Nisha Mishra,Female,19.0,5,68.5,NaN,NaN,67.7,5.25,...,2.2,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.30,...,4.7,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice
189,DS190,Neha Yadav,Female,23.0,6,61.4,4.9,59.9,69.8,53.50,...,5.0,84,0,Intermediate,Medium,61.3,70.4,C,High,Video Tutorials and Quizzes
191,DS192,Isha Sinha,Male,20.0,4,69.1,4.9,94.1,66.0,94.10,...,7.7,174,0,Intermediate,Medium,70.4,87.6,A,Medium,Advanced Projects
195,DS196,Aarav Verma,Female,22.0,6,56.9,4.3,90.3,86.9,70.30,...,5.5,22,4,Advanced,High,50.4,79.4,B,High,Practice Exercises

### Q28. Find students with mathematics_skill equal to 'Good' or 'Excellent'.

In [ ]:
df[df["mathematics_skill"].str.lower().isin(["good", "excellent"])]

Empty DataFrame
Columns: [student_id, student_name, gender, age, semester, attendance_percent, study_hours_per_day, assignment_average, quiz_average, mid_sem_score, previous_cgpa, lab_hours_per_week, online_activity_count, projects_completed, python_skill_level, mathematics_skill, engagement_score, predicted_score, grade, risk_level, learning_recommendation]
Index: []

[0 rows x 21 columns]

### Q29. Find students who completed at least 2 projects and have an engagement_score above 70.

In [ ]:
df[(df["projects_completed"] >= 2) & (df["engagement_score"] > 70)]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
15,DS016,Kavya Singh,Female,19.0,8,75.2,NaN,NaN,67.1,5.86,...,2.9,145,2,Intermediate,Medium,78.4,72.2,C,Low,Video Tutorials and Quizzes
18,DS019,Aarav Sharma,Female,NaN,3,72.8,NaN,NaN,48.6,8.22,...,2.9,136,2,Beginner,Medium,70.7,80.9,B,Medium,Practice Exercises
21,DS022,Ananya Gupta,Female,18.0,7,67.2,NaN,NaN,47.6,6.97,...,5.6,177,3,Beginner,High,77.4,81.8,B,Medium,Practice Exercises
25,DS026,Nisha Chauhan,Female,19.0,5,77.6,NaN,NaN,39.6,8.08,...,0.2,137,2,Advanced,Medium,72.8,78.1,B,Low,Practice Exercises
32,DS033,Aryan Kumar,Male,23.0,6,65.7,NaN,61.0,81.0,7.31,...,3.0,176,2,Beginner,Medium,74.5,83.8,B,Medium,Practice Exercises
35,DS036,Neha Kumar,Female,22.0,8,81.3,NaN,NaN,96.8,9.27,...,3.6,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects
37,DS038,Isha Gupta,Female,18.0,4,58.7,NaN,NaN,61.7,8.73,...,3.8,186,2,Intermediate,Medium,72.8,80.5,B,High,Practice Exercises
61,DS062,Isha Yadav,Female,18.0,6,73.9,5.6,64.9,74.8,76.10,...,5.3,90,3,Intermediate,Medium,70.5,78.4,B,Medium,Practice Exercises
65,DS066,Kavya Pandey,Male,23.0,5,98.3,5.7,52.8,64.4,56.10,...,5.1,170,4,Beginner,Low,83.8,75.2,B,Low,Practice Exercises
83,DS084,Riya Singh,Male,22.0,8,81.7,5.1,64.1,80.7,71.80,...,7.0,156,3,Advanced,High,73.7,81.6,B,Low,Practice Exercises
104,DS105,Nisha Gupta,Female,19.0,5,55.2,5.8,80.2,92.1,64.60,...,3.9,181,5,Beginner,Low,74.7,86.8,A,High,Advanced Projects
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.80,...,5.2,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
156,DS157,Nisha Singh,Male,19.0,8,72.1,5.9,63.5,57.8,94.70,...,6.1,130,2,Advanced,Medium,75.6,80.3,B,Medium,Practice Exercises
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.10,...,2.5,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises
175,DS176,Riya Kumar,Male,23.0,7,78.9,5.2,76.9,73.6,41.80,...,7.8,167,2,Intermediate,Low,74.7,75.7,B,Low,Practice Exercises
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.00,...,1.6,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects
184,DS185,Pooja Singh,Female,18.0,5,64.5,5.8,45.5,99.9,79.00,...,2.4,144,2,Intermediate,High,74.0,89.9,A,High,Advanced Projects
185,DS186,Neha Gupta,Male,22.0,7,92.0,5.0,93.6,82.0,41.80,...,5.8,137,3,Intermediate,Low,74.0,84.6,B,Low,Practice Exercises
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.90,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects

### Q30. Find students with attendance_percent above 85%, study_hours_per_day above 3, and grade A.

In [ ]:
df[(df["attendance_percent"] > 85) &
   (df["study_hours_per_day"] > 3) &
   (df["grade"].str.upper() == "A")]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.3,...,2.5,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.5,...,2.8,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

## D. Sorting and Ranking

### Q31. Sort the DataFrame by predicted_score in descending order.

In [ ]:
df.sort_values(by="predicted_score", ascending=False)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.70,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
14,DS015,Kunal Sharma,Male,20.0,5,93.5,NaN,NaN,95.8,8.77,...,5.4,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.40,...,2.4,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.40,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.50,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.70,...,6.5,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.40,...,1.8,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.90,...,6.6,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.50,...,7.4,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.10,...,1.1,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice

### Q32. Display the top 10 students according to predicted_score.

In [ ]:
df.sort_values(by="predicted_score", ascending=False).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.70,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
14,DS015,Kunal Sharma,Male,20.0,5,93.5,NaN,NaN,95.8,8.77,...,5.4,121,5,Advanced,High,57.1,95.9,A,Low,Advanced Projects
122,DS123,Saurabh Kumar,Female,19.0,8,91.8,2.9,93.3,92.1,87.40,...,2.4,82,4,Beginner,NaN,52.7,94.0,A,Low,Advanced Projects
49,DS050,Kunal Mishra,Female,20.0,5,55.8,4.5,99.8,93.8,72.40,...,0.0,127,0,Intermediate,Medium,60.1,93.9,A,High,Advanced Projects
129,DS130,Arjun Singh,Female,21.0,6,84.3,5.1,78.8,91.6,60.50,...,1.1,26,0,Advanced,High,64.0,93.5,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.90,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
179,DS180,Neha Singh,Male,20.0,6,73.1,6.0,93.4,77.4,72.00,...,1.6,94,3,Advanced,Medium,73.8,92.2,A,Medium,Advanced Projects
17,DS018,Arjun Sharma,Male,18.0,3,99.8,NaN,93.0,83.6,9.57,...,2.6,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects
119,DS120,Pooja Chauhan,Male,23.0,8,75.3,4.8,64.1,79.9,86.70,...,1.9,101,2,Beginner,High,65.3,91.1,A,Low,Advanced Projects
19,DS020,Aarav Sinha,Female,20.0,8,71.2,NaN,NaN,91.4,9.38,...,4.1,66,3,Intermediate,Medium,43.1,91.1,A,Medium,Advanced Projects

### Q33. Display the bottom 10 students according to predicted_score.

In [ ]:
df.sort_values(by="predicted_score", ascending=True).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
94,DS095,Aryan Singh,Female,21.0,3,78.3,1.4,64.3,42.0,40.10,...,1.1,112,1,Intermediate,High,39.7,60.0,D,Medium,Extra Mentoring and Practice
145,DS146,Aman Singh,Male,20.0,3,90.1,1.0,48.2,53.5,43.50,...,7.4,45,4,Beginner,Low,34.1,60.3,D,Medium,Extra Mentoring and Practice
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.90,...,6.6,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.40,...,1.8,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice
72,DS073,Saurabh Sinha,Female,20.0,5,58.5,1.0,98.2,40.3,41.70,...,6.5,58,4,Intermediate,Medium,27.3,61.2,D,High,Extra Mentoring and Practice
160,DS161,Isha Kumar,Female,23.0,5,55.0,1.8,66.4,62.8,49.70,...,1.0,156,5,Advanced,Medium,40.6,63.6,D,High,Extra Mentoring and Practice
36,DS037,Aryan Chauhan,Female,21.0,4,67.0,NaN,NaN,37.1,6.34,...,3.3,166,4,Advanced,High,52.4,63.8,D,Medium,Extra Mentoring and Practice
187,DS188,Vivaan Chauhan,Female,22.0,6,93.9,3.0,61.1,49.1,52.30,...,4.7,48,0,Intermediate,Medium,51.3,64.5,D,Medium,Extra Mentoring and Practice
10,DS011,Nisha Mishra,Female,19.0,5,68.5,NaN,NaN,67.7,5.25,...,2.2,138,2,Intermediate,Medium,47.4,65.0,C,Medium,Video Tutorials and Quizzes
174,DS175,Arjun Kumar,Female,19.0,6,74.4,1.7,94.0,60.8,45.00,...,5.2,172,2,Intermediate,High,46.0,65.1,C,Medium,Video Tutorials and Quizzes

### Q34. Find the student with the highest predicted_score.

In [ ]:
df.loc[df["predicted_score"].idxmax()]

student_id                             DS074
student_name                     Neha Pandey
gender                                  Male
age                                     20.0
semester                                   7
attendance_percent                      89.2
study_hours_per_day                      4.6
assignment_average                      80.0
quiz_average                            98.8
mid_sem_score                           93.7
previous_cgpa                            8.1
lab_hours_per_week                       5.5
online_activity_count                    118
projects_completed                         1
python_skill_level                  Beginner
mathematics_skill                     Medium
engagement_score                        68.5
predicted_score                         96.3
grade                                      A
risk_level                               Low
learning_recommendation    Advanced Projects
Name: 73, dtype: object

### Q35. Find the student with the lowest predicted_score.

In [ ]:
df.loc[df["predicted_score"].idxmin()]

student_id                                        DS095
student_name                                Aryan Singh
gender                                           Female
age                                                21.0
semester                                              3
attendance_percent                                 78.3
study_hours_per_day                                 1.4
assignment_average                                 64.3
quiz_average                                       42.0
mid_sem_score                                      40.1
previous_cgpa                                      6.91
lab_hours_per_week                                  1.1
online_activity_count                               112
projects_completed                                    1
python_skill_level                         Intermediate
mathematics_skill                                  High
engagement_score                                   39.7
predicted_score                                    60.0
grade                                                 D
risk_level                                       Medium
learning_recommendation    Extra Mentoring and Practice
Name: 94, dtype: object

### Q36. Sort students by previous_cgpa in descending order.

In [ ]:
df.sort_values(by="previous_cgpa", ascending=False)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
142,DS143,Isha Verma,Female,23.0,3,74.5,1.4,57.1,75.9,82.80,...,7.5,54,0,Intermediate,Medium,34.1,79.9,B,Medium,Practice Exercises
139,DS140,Kavya Sinha,Male,19.0,7,71.6,2.6,53.2,58.3,92.00,...,2.9,134,3,Intermediate,High,49.4,80.5,B,Medium,Practice Exercises
93,DS094,Ananya Sinha,Female,18.0,6,90.1,1.2,71.4,46.3,50.70,...,1.1,89,5,Intermediate,Medium,39.2,72.7,C,Low,Video Tutorials and Quizzes
90,DS091,Rahul Singh,Male,22.0,5,56.4,4.3,65.3,91.9,65.80,...,1.5,154,4,Intermediate,High,60.8,86.3,A,High,Advanced Projects
178,DS179,Isha Sharma,Male,19.0,4,66.7,2.0,48.2,60.5,52.60,...,4.5,138,3,Intermediate,High,43.7,70.2,C,Medium,Video Tutorials and Quizzes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,DS040,Riya Gupta,Male,23.0,3,60.8,NaN,NaN,78.7,7.97,...,NaN,81,1,Intermediate,Medium,68.1,84.2,B,High,Practice Exercises
40,DS041,Simran Kumar,Male,23.0,6,80.2,NaN,48.0,36.9,8.62,...,5.0,75,2,Beginner,Low,69.2,76.8,B,Low,Practice Exercises
41,DS042,Vivaan Yadav,Female,19.0,4,83.6,NaN,NaN,70.6,7.16,...,7.3,39,1,Advanced,High,54.4,78.4,B,Low,Practice Exercises
43,DS044,Pooja Pandey,Male,21.0,6,70.6,NaN,NaN,46.2,5.92,...,0.3,14,1,Beginner,Low,62.8,76.7,B,Medium,Practice Exercises
44,DS045,Rahul Kumar,Male,22.0,3,71.0,NaN,NaN,55.9,5.44,...,3.8,65,5,Beginner,Medium,67.0,70.0,C,Medium,Video Tutorials and Quizzes

### Q37. Sort students first by semester and then by predicted_score in descending order.

In [ ]:
df.sort_values(by=["semester", "predicted_score"], ascending=[True, False])

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
17,DS018,Arjun Sharma,Male,18.0,3,99.8,NaN,93.0,83.6,9.57,...,2.6,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,4.2,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects
135,DS136,Aman Kumar,Male,21.0,3,79.5,4.2,57.2,98.7,83.60,...,1.4,95,5,Advanced,High,61.1,86.8,A,Low,Advanced Projects
196,DS197,Arjun Chauhan,Male,20.0,3,88.1,2.7,94.8,56.0,82.10,...,0.3,99,5,Intermediate,Medium,51.5,86.8,A,Low,Advanced Projects
188,DS189,Isha Gupta,Male,20.0,3,89.2,1.9,84.6,92.0,64.50,...,4.4,157,1,Beginner,Medium,50.1,85.6,A,Low,Advanced Projects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,DS093,Pooja Sinha,Female,21.0,8,81.2,2.3,88.9,58.6,64.60,...,0.6,73,1,Intermediate,Medium,44.5,69.7,C,Low,Video Tutorials and Quizzes
85,DS086,Simran Verma,Male,19.0,8,89.0,2.3,55.6,45.0,56.20,...,0.9,107,3,Beginner,High,49.2,67.9,C,Low,Video Tutorials and Quizzes
75,DS076,Saurabh Mishra,Male,18.0,8,81.8,2.2,51.6,44.6,80.30,...,5.8,117,0,Intermediate,Medium,47.4,67.3,C,Low,Video Tutorials and Quizzes
167,DS168,Sneha Kumar,Male,20.0,8,82.5,2.4,56.4,71.0,35.40,...,1.8,52,3,Beginner,Medium,44.0,61.1,D,Medium,Extra Mentoring and Practice
162,DS163,Isha Verma,Male,23.0,8,60.4,1.3,59.5,42.8,71.90,...,6.6,62,2,Beginner,Medium,30.5,60.8,D,High,Extra Mentoring and Practice

### Q38. Rank all students based on predicted_score.

In [ ]:
df["predicted_score_rank"] = df["predicted_score"].rank(ascending=False, method="min")
df[["student_name", "predicted_score", "predicted_score_rank"]].sort_values("predicted_score_rank")

      student_name  predicted_score  predicted_score_rank
73     Neha Pandey             96.3                   1.0
14    Kunal Sharma             95.9                   2.0
122  Saurabh Kumar             94.0                   3.0
49    Kunal Mishra             93.9                   4.0
129    Arjun Singh             93.5                   5.0
..             ...              ...                   ...
72   Saurabh Sinha             61.2                 196.0
167    Sneha Kumar             61.1                 197.0
162     Isha Verma             60.8                 198.0
145     Aman Singh             60.3                 199.0
94     Aryan Singh             60.0                 200.0

[200 rows x 3 columns]

### Q39. Display the top 10 students based on engagement_score.

In [ ]:
df.sort_values(by="engagement_score", ascending=False).head(10)

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation,predicted_score_rank
65,DS066,Kavya Pandey,Male,23.0,5,98.3,5.7,52.8,64.4,56.10,...,170,4,Beginner,Low,83.8,75.2,B,Low,Practice Exercises,124.0
126,DS127,Kavya Sharma,Female,21.0,3,77.9,6.0,89.8,76.9,54.90,...,187,4,Advanced,Medium,82.4,89.1,A,Low,Advanced Projects,17.0
107,DS108,Vivaan Singh,Female,23.0,3,94.0,6.0,86.4,45.4,53.80,...,111,5,Advanced,Medium,80.4,78.0,B,Low,Practice Exercises,102.0
112,DS113,Saurabh Verma,Female,23.0,4,73.0,5.9,90.3,71.3,43.00,...,168,0,Intermediate,Medium,78.9,88.1,A,Medium,Advanced Projects,19.0
15,DS016,Kavya Singh,Female,19.0,8,75.2,NaN,NaN,67.1,5.86,...,145,2,Intermediate,Medium,78.4,72.2,C,Low,Video Tutorials and Quizzes,147.0
98,DS099,Aditya Yadav,Male,18.0,6,62.8,5.8,67.9,90.8,75.90,...,197,1,Advanced,Medium,77.9,90.3,A,High,Advanced Projects,12.0
158,DS159,Pooja Yadav,Male,18.0,7,91.3,5.2,59.0,41.9,83.10,...,165,5,Advanced,Medium,77.6,75.1,B,Low,Practice Exercises,127.0
35,DS036,Neha Kumar,Female,22.0,8,81.3,NaN,NaN,96.8,9.27,...,165,4,Beginner,Low,77.5,88.0,A,Low,Advanced Projects,20.0
21,DS022,Ananya Gupta,Female,18.0,7,67.2,NaN,NaN,47.6,6.97,...,177,3,Beginner,High,77.4,81.8,B,Medium,Practice Exercises,63.0
16,DS017,Isha Yadav,Female,23.0,8,81.5,NaN,NaN,63.2,6.68,...,120,0,Beginner,Medium,77.2,87.1,A,Low,Advanced Projects,26.0

### Q40. Find the student with the highest online_activity_count.

In [ ]:
df.loc[df["online_activity_count"].idxmax()]

student_id                                       DS034
student_name                              Aditya Singh
gender                                          Female
age                                               21.0
semester                                             8
attendance_percent                                57.5
study_hours_per_day                                NaN
assignment_average                                79.0
quiz_average                                      83.5
mid_sem_score                                      7.8
previous_cgpa                                      NaN
lab_hours_per_week                                 7.7
online_activity_count                              200
projects_completed                                   3
python_skill_level                            Beginner
mathematics_skill                                 High
engagement_score                                  43.2
predicted_score                                   72.4
grade                                                C
risk_level                                        High
learning_recommendation    Video Tutorials and Quizzes
predicted_score_rank                             146.0
Name: 33, dtype: object

## E. GroupBy and Aggregation

### Q41. Calculate the average predicted_score for each semester.

In [ ]:
df.groupby("semester")["predicted_score"].mean().sort_index()

semester
3    77.084615
4    78.380000
5    79.244737
6    77.290909
7    77.473529
8    77.491176
Name: predicted_score, dtype: float64

### Q42. Calculate the average attendance_percent for each semester.

In [ ]:
df.groupby("semester")["attendance_percent"].mean().sort_index()

semester
3    79.284615
4    75.508571
5    73.623684
6    79.024242
7    78.608824
8    79.679412
Name: attendance_percent, dtype: float64

### Q43. Find the average study_hours_per_day for each gender.

In [ ]:
df.groupby("gender")["study_hours_per_day"].mean()

gender
Female    3.361333
Male      3.421250
Name: study_hours_per_day, dtype: float64

### Q44. Count the number of students in each grade.

In [ ]:
df["grade"].value_counts()

grade
B    86
C    65
A    41
D     8
Name: count, dtype: int64

### Q45. Count the number of students in each risk_level.

In [ ]:
df["risk_level"].value_counts()

risk_level
Low       111
Medium     52
High       37
Name: count, dtype: int64

### Q46. Calculate the average predicted_score for each python_skill_level.

In [ ]:
df.groupby("python_skill_level")["predicted_score"].mean()

python_skill_level
Advanced        78.751220
Beginner        77.455385
Intermediate    77.817021
Name: predicted_score, dtype: float64

### Q47. Calculate the average previous_cgpa for each mathematics_skill level.

In [ ]:
df.groupby("mathematics_skill")["previous_cgpa"].mean()

mathematics_skill
High      7.558750
Low       7.104545
Medium    7.355405
Name: previous_cgpa, dtype: float64

### Q48. Find the average engagement_score for each semester.

In [ ]:
df.groupby("semester")["engagement_score"].mean().sort_index()

semester
3    54.403846
4    57.934286
5    55.778947
6    56.184848
7    53.920588
8    54.091176
Name: engagement_score, dtype: float64

### Q49. Calculate the maximum and minimum predicted_score for each grade.

In [ ]:
df.groupby("grade")["predicted_score"].agg(["max", "min"])

        max   min
grade
A      96.3  85.0
B      84.9  75.1
C      74.8  65.0
D      64.5  60.0

### Q50. Create a grouped summary by semester containing average attendance, average study hours, average predicted score, and number of students.

In [ ]:
semester_summary = df.groupby("semester").agg(
    average_attendance=("attendance_percent", "mean"),
    average_study_hours=("study_hours_per_day", "mean"),
    average_predicted_score=("predicted_score", "mean"),
    number_of_students=("student_id", "count")
).reset_index()

semester_summary

,semester,average_attendance,average_study_hours,average_predicted_score,number_of_students
0,3,79.284615,2.810000,77.084615,26
1,4,75.508571,3.696296,78.380000,35
2,5,73.623684,3.630000,79.244737,38
3,6,79.024242,3.644000,77.290909,33
4,7,78.608824,3.322222,77.473529,34
5,8,79.679412,3.080769,77.491176,34

## Assignment Complete

All 50 questions are included above in Google Colab-ready format.

**Tip:** Run the notebook from top to bottom after uploading `students.csv`.